# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{textile_editor}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ben Mills"]
  s.date = %q{2010-11-15}
  s.email = %q{ben@unfiniti.com}
  s.files = [
    ".bundle/config",
     ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "Rakefile",
     "VERSION",
     "lib/textile_editor.rb",
     "textile_editor.gemspec",
     "test/abstract_unit.rb",
     "test/textile_editor_test.rb"
  ]
  s.homepage = %q{http://unfiniti.com}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Provide textile toolbar to textareas}
  s.test_files = [
    "test/abstract_unit.rb",
    "test/textile_editor_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3
  end
end

